SENDGRID_PASSWORD: 7dsnq7di
SENDGRID_USERNAME: app29299919@heroku.com
DEVISE_SECRET_KEY: 598548d4afa8241140ff9020d7011ee566747b9682d85c8e0d585d1a96fc1d688005fdd0fa5cb704ecaf6d2fb786b2b68f9dddecb6d472d47b2d37e138101092
AWS_ACCESS_KEY_ID: AKIAIJXMYHF3VIC2VCIQ
AWS_SECRET_ACCESS_KEY: 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
development:
 AWS_BUCKET: Amanjot-Kaur-bloccit-development
production:
 AWS_BUCKET: Amanjot-Kaur-bloccit-production	

# Add application configuration variables here, as shown below.

# PUSHER_APP_ID: "2954"
# PUSHER_KEY: 7381a978f7dd7f9a1117
# PUSHER_SECRET: abdc3b896a0ffb85d373
# STRIPE_API_KEY: EdAvEPVEC3LuaTg5Q3z6WbDVqZlcBQ8Z
# STRIPE_PUBLIC_KEY: pk_BRgD57O8fHja9HxduJUszhef6jCyS
